micronaut:
  application:
    name: studentServiceMicronaut
  server:
    port: 8090
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/actor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: NONE
    dialect: POSTGRES
    schema: public
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  entity-scan:
    packages: 'com.example.model'
training:
  name: darek
  age: ${random.int[1,99]}
  port: ${random.port}
  uuid: ${random.uuid}
  zagadka: zagadka zimowa
